### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Saint-Theana** [mabe02/lanterna#420]
i was trying to create a actionlistbox,I got following Exception;I think that hapened because length of itemtext was bigger than window's width.this also hapened when I tried to create a table.When I use shotter itemtext,this erro would not hapen.

java.lang.ArrayIndexOutOfBoundsException: 1
	at com.googlecode.lanterna.gui2.GridLayout.shrinkWidthToFitArea(GridLayout.java:669)
	at com.googlecode.lanterna.gui2.GridLayout.doLayout(GridLayout.java:428)
	at com.googlecode.lanterna.gui2.Panel.layout(Panel.java:392)
	at com.googlecode.lanterna.gui2.Panel.access$300(Panel.java:38)
	at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:234)
	at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:221)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:218)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:340)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:324)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:218)
	at com.googlecode.lanterna.gui2.AbstractBasePane.draw(AbstractBasePane.java:73)
	at com.googlecode.lanterna.gui2.AbstractWindow.draw(AbstractWindow.java:128)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:261)
	at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:120)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:223)
	at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:85)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:409)
	at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:269)
	at com.Tick_Tock.PCTIM.Main.main(Main.java:109)

**Comment by mabe02** [comment]
Do you think you can provide a minimal code sample that reproduces this error? It's probably another bug in the GridLayout.

**Comment by Saint-Theana** [comment]
Exception window:
```java
package com.Tick_Tock.PCTIM.Window;
import com.googlecode.lanterna.gui2.*;
import java.util.*;
import com.Tick_Tock.PCTIM.*;
import com.googlecode.lanterna.gui2.table.*;
import com.Tick_Tock.PCTIM.sdk.*;
import com.Tick_Tock.PCTIM.Utils.*;

public class FriendListWindow extends BasicWindow
{

	private Panel contentPanel;

	private ActionListBox actionListBox;

	
	public FriendListWindow(String title){
		super(title);
		this.setHints(Arrays.asList(Window.Hint.FIXED_SIZE,Window.Hint.NO_POST_RENDERING));
		this.actionListBox = new ActionListBox(this.getSize());
		
		
		this.contentPanel = new Panel(new GridLayout(2)); // can hold multiple sub-components that will be added to a windo
		
		this.contentPanel.addComponent(this.actionListBox,GridLayout.createLayoutData(GridLayout.Alignment.BEGINNING, GridLayout.Alignment.CENTER));
		
		
        
		
		this.setComponent(this.contentPanel);
		
	}


	
	
	public void setfriendlist(final QQUser user){
		
		if(user.friend_list!=null){
			for(Friend_List.Friend members:user.friend_list.members){
			  FriendListWindow.this.actionListBox.addItem(members+"    Temporary Nothing",new Runnable(){
				@Override  public void run(){
					  
				  }
			  });
			}
			
		}else{
			
		}
	
	}




}
```

**Comment by Saint-Theana** [comment]
Main Class:
```java
package com.Tick_Tock.PCTIM;

import java.util.*;
import com.Tick_Tock.PCTIM.Socket.*;
import com.Tick_Tock.PCTIM.Package.SendPackageFactory;
import com.Tick_Tock.PCTIM.Utils.*;
import com.Tick_Tock.PCTIM.Package.*;
import com.Tick_Tock.PCTIM.Robot.*;
import com.Tick_Tock.PCTIM.TLV.*;
import javax.net.ssl.*;
import com.Tick_Tock.PCTIM.Window.*;
import com.googlecode.lanterna.terminal.ansi.*;
import com.googlecode.lanterna.screen.*;
import com.googlecode.lanterna.gui2.*;
import com.googlecode.lanterna.*;
import com.googlecode.lanterna.terminal.*;


public class Main
{
	public static void main(final String[] args)
	{
		Terminal term = null;

		Screen screen = null;

		try
		{
			Util.trustAllHttpsCertificates();

			HttpsURLConnection.setDefaultHostnameVerifier(Util.hv);

            // Swing is the default backend on Windows unless explicitly
            // overridden by jexer.Swing.
            
			term = new UnixTerminal();
			screen = new TerminalScreen(term);
			screen.startScreen();
			WindowBasedTextGUI textGUI = new MultiWindowTextGUI(screen);
			TerminalSize size = screen.getTerminalSize();
			
			QQUser user = null ;
			String qq =Util.read_property("account");
			String password = Util.read_property("password");
			byte[] passwordmd5=new byte[0];
			LoginManager manager = null ;
			if (qq == null || password == null)
			{
				LoginWindow loginwindow = new LoginWindow("登录");
				textGUI.addWindow(loginwindow);
				loginwindow.waitUntilClosed();
				qq=loginwindow.account();
				passwordmd5=Util.MD5(loginwindow.password());
				user = new QQUser(Long.parseLong(qq), passwordmd5);
				manager = new LoginManager(Long.parseLong(qq), passwordmd5);
		
				}
			else
			{
				passwordmd5 = Util.str_to_byte(password);
				user = new QQUser(Long.parseLong(qq), passwordmd5);
				manager = new LoginManager(Long.parseLong(qq), passwordmd5);
				

			}
			
			OutPutWindow processingloginoutputwindow = new OutPutWindow("登录日志");
			processingloginoutputwindow.setSize(new TerminalSize(size.getColumns()-2,size.getRows()-2));
			processingloginoutputwindow.setlogsize(new TerminalSize(size.getColumns()-3,size.getRows()-3));
			
			textGUI.addWindow(processingloginoutputwindow);
			processingloginoutputwindow.setPosition(new TerminalPosition(0,0));
			Util.output=processingloginoutputwindow;
			manager.st(processingloginoutputwindow);
			processingloginoutputwindow.waitUntilClosed();
			
			
			
            FriendListWindow friendlistwindow = new FriendListWindow("好友列表");
			Window grouplistwindow = new GroupListWindow("群列表");
			Window chatwindow = new ChatWindow("聊天");
			OutPutWindow logoutputwindow = new OutPutWindow("日志");
			


			


			friendlistwindow.setSize(new TerminalSize(size.getColumns()/3-2,size.getRows()/2-2));
			
			grouplistwindow.setSize(new TerminalSize(size.getColumns()/3-2,size.getRows()/2-2));
			chatwindow.setSize(new TerminalSize(size.getColumns()/3-2,size.getRows()/2-2));
			logoutputwindow.setSize(new TerminalSize(size.getColumns()-2,size.getRows()/2-2));
			logoutputwindow.setlogsize(new TerminalSize(size.getColumns()-3,size.getRows()/2-3));

			textGUI.addWindow(friendlistwindow);
			textGUI.addWindow(grouplistwindow);
			textGUI.addWindow(chatwindow);
			textGUI.addWindow(logoutputwindow);
			textGUI.setActiveWindow(friendlistwindow);

			friendlistwindow.setPosition(new TerminalPosition(0,0));
			grouplistwindow.setPosition(new TerminalPosition(size.getColumns()/3,0));
			chatwindow.setPosition(new TerminalPosition((size.getColumns()/3)*2,0));
			logoutputwindow.setPosition(new TerminalPosition(0,size.getRows()/2));
			new qqinfo().setuser(manager.user).setfriendwindow(friendlistwindow).start();
	
			Util.output=logoutputwindow;
			friendlistwindow.waitUntilClosed();
			
			
			
        }
		catch (Exception e)
		{
            e.printStackTrace();
        }
	
		
		
		

	}

	




}

class qqinfo extends Thread
{

	private QQUser user;

	private FriendListWindow friendlistwindow;

	public qqinfo setuser(QQUser _user){
		this.user=_user;
		return this;
	}
	public qqinfo setfriendwindow(FriendListWindow window){
		this.friendlistwindow=window;
		return this;
	}
	

	@Override public void run(){
		Util.getquncookie(this.user);
		Util.getqunlist(this.user);
		Util.getfriendlist(this.user);
		this.friendlistwindow.setfriendlist(this.user);
	}
}
```

**Comment by Saint-Theana** [comment]
Main Class
```java
package com.Tick_Tock.PCTIM;

import java.util.*;
import com.Tick_Tock.PCTIM.Socket.*;
import com.Tick_Tock.PCTIM.Package.SendPackageFactory;
import com.Tick_Tock.PCTIM.Utils.*;
import com.Tick_Tock.PCTIM.Package.*;
import com.Tick_Tock.PCTIM.Robot.*;
import com.Tick_Tock.PCTIM.TLV.*;
import javax.net.ssl.*;
import com.Tick_Tock.PCTIM.Window.*;
import com.googlecode.lanterna.terminal.ansi.*;
import com.googlecode.lanterna.screen.*;
import com.googlecode.lanterna.gui2.*;
import com.googlecode.lanterna.*;
import com.googlecode.lanterna.terminal.*;


public class Main
{
	public static void main(final String[] args)
	{
		Terminal term = null;

		Screen screen = null;

		try
		{
			Util.trustAllHttpsCertificates();

			HttpsURLConnection.setDefaultHostnameVerifier(Util.hv);

            // Swing is the default backend on Windows unless explicitly
            // overridden by jexer.Swing.
            
			term = new UnixTerminal();
			screen = new TerminalScreen(term);
			screen.startScreen();
			WindowBasedTextGUI textGUI = new MultiWindowTextGUI(screen);
			TerminalSize size = screen.getTerminalSize();
			
			QQUser user = null ;
			String qq =Util.read_property("account");
			String password = Util.read_property("password");
			byte[] passwordmd5=new byte[0];
			LoginManager manager = null ;
			if (qq == null || password == null)
			{
				LoginWindow loginwindow = new LoginWindow("Login");
				textGUI.addWindow(loginwindow);
				loginwindow.waitUntilClosed();
				qq=loginwindow.account();
				passwordmd5=Util.MD5(loginwindow.password());
				user = new QQUser(Long.parseLong(qq), passwordmd5);
				manager = new LoginManager(Long.parseLong(qq), passwordmd5);
		
				}
			else
			{
				passwordmd5 = Util.str_to_byte(password);
				user = new QQUser(Long.parseLong(qq), passwordmd5);
				manager = new LoginManager(Long.parseLong(qq), passwordmd5);
				

			}
			
			OutPutWindow processingloginoutputwindow = new OutPutWindow("Login log");
			processingloginoutputwindow.setSize(new TerminalSize(size.getColumns()-2,size.getRows()-2));
			processingloginoutputwindow.setlogsize(new TerminalSize(size.getColumns()-3,size.getRows()-3));
			
			textGUI.addWindow(processingloginoutputwindow);
			processingloginoutputwindow.setPosition(new TerminalPosition(0,0));
			Util.output=processingloginoutputwindow;
			manager.st(processingloginoutputwindow);
			processingloginoutputwindow.waitUntilClosed();
			
			
			
            FriendListWindow friendlistwindow = new FriendListWindow("Friend List");
			Window grouplistwindow = new GroupListWindow("Group List");
			Window chatwindow = new ChatWindow("Chat");
			OutPutWindow logoutputwindow = new OutPutWindow("Log");
			


			


			friendlistwindow.setSize(new TerminalSize(size.getColumns()/3-2,size.getRows()/2-2));
			
			grouplistwindow.setSize(new TerminalSize(size.getColumns()/3-2,size.getRows()/2-2));
			chatwindow.setSize(new TerminalSize(size.getColumns()/3-2,size.getRows()/2-2));
			logoutputwindow.setSize(new TerminalSize(size.getColumns()-2,size.getRows()/2-2));
			logoutputwindow.setlogsize(new TerminalSize(size.getColumns()-3,size.getRows()/2-3));

			textGUI.addWindow(friendlistwindow);
			textGUI.addWindow(grouplistwindow);
			textGUI.addWindow(chatwindow);
			textGUI.addWindow(logoutputwindow);
			textGUI.setActiveWindow(friendlistwindow);

			friendlistwindow.setPosition(new TerminalPosition(0,0));
			grouplistwindow.setPosition(new TerminalPosition(size.getColumns()/3,0));
			chatwindow.setPosition(new TerminalPosition((size.getColumns()/3)*2,0));
			logoutputwindow.setPosition(new TerminalPosition(0,size.getRows()/2));
			new qqinfo().setuser(manager.user).setfriendwindow(friendlistwindow).start();
	
			Util.output=logoutputwindow;
			friendlistwindow.waitUntilClosed();
			
			
			
        }
		catch (Exception e)
		{
            e.printStackTrace();
        }
	
		
		
		

	}

	




}

class qqinfo extends Thread
{

	private QQUser user;

	private FriendListWindow friendlistwindow;

	public qqinfo setuser(QQUser _user){
		this.user=_user;
		return this;
	}
	public qqinfo setfriendwindow(FriendListWindow window){
		this.friendlistwindow=window;
		return this;
	}
	

	@Override public void run(){
		Util.getquncookie(this.user);
		Util.getqunlist(this.user);
		Util.getfriendlist(this.user);
		this.friendlistwindow.setfriendlist(this.user);
	}
}
```

**Comment by Saint-Theana** [comment]
here is the bug sample:
https://github.com/Saint-Theana/lanterna_learn

**Comment by mabe02** [comment]
Thanks, I've fixed the bug and pushed to the release branch.

You can work around it by changing your GridLayout to only one column since you only have one component:
`this.contentPanel = new Panel(new GridLayout(2))` -> `this.contentPanel = new Panel(new GridLayout(1))`

Also, I'd strongly recommend you start formatting your code using general java code style conventions.

**Comment by Saint-Theana** [comment]
thanks for your help,but this problem is still unsolved,long itemtext still cannot be shown normally in Table/ActionListBox.

**Comment by Saint-Theana** [comment]
about your concern about my java coding style,Im not a software developer,I treat programing as a hobit,I like it,but I don't like computer,my code was completely written with app AIDE on Android Phone.It not big deal for me that the codes I wrote was hard to read,sorry that cause your trouble.😃

**Comment by mabe02** [comment]
Are you sure you ran with the latest release/3.0 branch code? I haven't created a new Maven release yet. The example you sent above worked for me with the latest snapshot code.

**Comment by Saint-Theana** [comment]
I clone'd the source code from this repo... and build the library myself.
And there is one more trouble botherring me,I had to pack lanterna library class and my Project class into one jar,or the terminal cannot run.
I will try the 3.0.0 release on maven.

**Comment by Saint-Theana** [comment]
Table seems fine on release 3.0.0 .

**Comment by avl42** [comment]
I'm not a maven expert,  but rather than merging lanterna with your code (which might also be problematic with lanterna's LGPL, unless your code is (L)GPL as well),  you might rather try to tell maven that your project simply depends on lanterna, and let maven sort out the details...

**Comment by avl42** [comment]
maybe, being more verbose on "or the terminal cannot run" could also help ;-)
